## Model Tuning / Hyperparameter Tuning

- Every model has parameter, changing the parameter effects the accuracy of that model.
- For particular model best parameter should be choosen, hence we use Hyperparameter Tuning.

1. Manual Search
2. Grid Search CV
3. Randomized Search

### 1.Manual Search

- Note: It is used very less because we need to manual change the parameter and decided which parmeter is best. It is not efficient.

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 

import warnings 
warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [4]:
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X = df.drop('species',axis=1)
y = df['species']

In [9]:
X.head()

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [11]:
from sklearn.neighbors import KNeighborsClassifier

In [12]:
model_knn = KNeighborsClassifier(n_neighbors=5)  #changing n_neighnors value to 3,9,13 to see the score

In [13]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier()

In [15]:
model_knn.score(X_test, y_test)

0.98

In [16]:
from sklearn.svm import SVC

In [31]:
model_SVM = SVC(gamma= 'auto')

In [32]:
model_SVM.fit(X_train,y_train)

SVC(gamma='auto')

In [33]:
model_SVM.score(X_test, y_test)

1.0

In [35]:
#Using Grid Search CV 

from sklearn.model_selection import GridSearchCV

In [36]:
classifier = GridSearchCV((model_SVM), {
    'C': [1,10,20,30,50], 
    'kernel': ['rbf','linear']
},cv=5,return_train_score=False)

In [37]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30, 50], 'kernel': ['rbf', 'linear']})

In [38]:
classifier.cv_results_

{'mean_fit_time': array([0.00442715, 0.00526466, 0.00331135, 0.00325146, 0.0033175 ,
        0.0027051 , 0.00301661, 0.00281525, 0.00291405, 0.00332961]),
 'std_fit_time': array([0.00048857, 0.00111281, 0.00086764, 0.00024556, 0.00113014,
        0.00040265, 0.00031095, 0.0005118 , 0.00050532, 0.00068723]),
 'mean_score_time': array([0.00371284, 0.00381846, 0.00241528, 0.00200067, 0.00200367,
        0.00221419, 0.00202065, 0.00200386, 0.00234389, 0.00219412]),
 'std_score_time': array([4.02493367e-04, 5.28778964e-04, 5.72475997e-04, 1.63323514e-05,
        9.12118566e-06, 2.58007549e-04, 3.73800188e-05, 1.26747227e-05,
        4.34988487e-04, 4.03955193e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30, 50, 50],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'},
  {'C': 50, 'kernel': 'rbf'},
  {'C': 50, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        , 1.        , 1.        ]),
 'split1_test_score': array([1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 0.96666667, 1.        ]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       , 0.93333333, 0.93333333]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      , 0.96      , 0.96666667]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979, 0.03887301, 0.0421637 ]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 8, 8, 8, 6])}

In [39]:
results = pd.DataFrame(classifier.cv_results_)

In [40]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004427,0.000489,0.003713,0.000402,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.005265,0.001113,0.003818,0.000529,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.003311,0.000868,0.002415,0.000572,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.003251,0.000246,0.002001,0.000016,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.003317,0.001130,0.002004,0.000009,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.002705,0.000403,0.002214,0.000258,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.003017,0.000311,0.002021,0.000037,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.933333,1.0,0.960000,0.038873,8
7,0.002815,0.000512,0.002004,0.000013,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,8
8,0.002914,0.000505,0.002344,0.000435,50,rbf,"{'C': 50, 'kernel': 'rbf'}",1.000000,0.966667,0.900000,0.933333,1.0,0.960000,0.038873,8
9,0.003330,0.000687,0.002194,0.000404,50,linear,"{'C': 50, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6

In [41]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000
8       50          rbf         0.960000
9       50       linear         0.966667

In [42]:
from sklearn.model_selection import RandomizedSearchCV

In [43]:
classifier_r = RandomizedSearchCV((model_SVM),{
    'C': [1,10,20,30,50], 
    'kernel': ['rbf','linear']
},n_iter=5, cv=5,return_train_score=False)

In [44]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=5,
                   param_distributions={'C': [1, 10, 20, 30, 50],
                                        'kernel': ['rbf', 'linear']})

In [47]:
results = pd.DataFrame(classifier_r.cv_results_)

In [48]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1       20       linear         0.966667
2       50       linear         0.966667
3       10       linear         0.973333
4       50          rbf         0.960000