## Index

- Series
- Data Frames
- Missing Data
- Merging, Joining concatination
- GroupBy and Aggregations
- Pivot Tables and Crosstab
- Operatios
- Working with real data

## Pandas Series
- A series is a one-dimensional labeled array capable of holding any data type. The axis lables are collectively called the index.

### Creating Series (There are multiple ways to create a pandas series)

In [2]:
import numpy as np 
import pandas as pd

In [3]:
labels = ['a','b','c']
my_list= [10,20,30]
arr = np.array([10,20,30])
d = {1:10,2:20,3:30}

In [4]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(arr,index=labels)

a    10
b    20
c    30
dtype: int32

In [7]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

## Data Frames

### Creating a DataFrame

In [8]:
#Creating a DataFrame from Dict

data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [9]:
df  #when we target multiple series(columns) we call it data-frames

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
#Creating a DataFrame from Lists

data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

df2  = pd.DataFrame(data_list)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [11]:
columns = ['Name','Age','City','Salary']
df2 = pd.DataFrame(data_list,columns= columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

### Selection and Indexing of Columns

In [17]:
df2[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

### Creating a new ccolumns

In [18]:

df2["Designation"] = ['Engineer','Doctor','Lawer','Police']

In [19]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000    Engineer
1   Anna   34     Paris   70000      Doctor
2  Peter   29    Berlin   62000       Lawer
3  Linda   42    London   85000      Police

### Removing Columns

In [20]:
df2.drop('Designation', axis=1)   #Axis=0(rows)  Axis= 1(columns)
#Copy version

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [21]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000    Engineer
1   Anna   34     Paris   70000      Doctor
2  Peter   29    Berlin   62000       Lawer
3  Linda   42    London   85000      Police

In [22]:
df2.drop('Designation', axis=1, inplace=True)   #Axis=0(rows)  Axis= 1(columns)

In [23]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [24]:
#Remove multiple ccolumns
df2.drop(['Age','City'], axis=1)

    Name  Salary
0   John   65000
1   Anna   70000
2  Peter   62000
3  Linda   85000

In [25]:
#Remove multiple ccolumns
df2.drop(2, axis=0)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
3  Linda   42    London   85000

### Selecting Rows

In [27]:
df2[0]

KeyError: 0

In [26]:
df2.loc[0]   #loc (location) is used for rows as writing only df2[0] will give error

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [28]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [29]:
df2.iloc[3]  #iloc = index location

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

### Selecting Subsets of Rows and Columns

In [30]:
df2.loc[[0,1]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [31]:
df2.loc[[2,3]][['Name','Age']]

    Name  Age
2  Peter   29
3  Linda   42

### Conditional Selection

In [32]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [33]:
#people with age above 30

df2[df2["Age"]> 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [41]:
# Error but solved below
df2[df2["Age"]> 30 & df2["City"] == 'Paris']

TypeError: Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]

In [40]:
df2[(df2["Age"]> 30) & (df2["City"] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

### Finding Missing Data

In [53]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}

df = pd.DataFrame(data)

In [54]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [55]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [57]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [58]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

### Removing Missing Data

In [59]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [60]:
df.dropna()  #removes rows which has null values present

     A  B    C    D
0  1.0  1  1.0  1.0

In [61]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [63]:
df.dropna(thresh=3)  #3 non-null should be present in each rows or else they will be removed

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [64]:
df.dropna(thresh=2)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

### Filling the missing data

In [65]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [66]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [67]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [68]:
values = {'A':0,'B':100,'C':300,'D':400}
df.fillna(value= values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [72]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [73]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

### Merging Joining, Concatination

#### Merging 2 Dataframes

In [74]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [77]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [78]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [79]:
pd.merge(employees,salaries,on='employee_id',how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [80]:
pd.merge(employees,salaries,on='employee_id',how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [81]:
pd.merge(employees,salaries,on='employee_id',how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [82]:
pd.merge(employees,salaries,on='employee_id',how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

#### Concatination 2 Dataframes

In [83]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [84]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [85]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [86]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [87]:
pd.concat([df2,df1])

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [88]:
pd.concat([df1,df2], axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

#### Joining 2 Dataframes

In [89]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [90]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [91]:
df2

   score
2     85
3     90
4     75

In [92]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [93]:
df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

### GroupByAggregation

#### GroupBy

In [94]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [95]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [96]:
# Group by Category and calculate the sum of Sales
df.groupby('Category')

In [97]:
cat = df.groupby('Category')
cat
for i, v in cat:
    print(i)
    print(v)

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [98]:
cat = df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [99]:
# Group by Store and calculate the sum of Sales
st = df.groupby("Store")["Sales"].sum()
st

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [102]:
# Group by multiple columns
# Group by Category and Store
st = df.groupby(['Category',"Store"])["Sales"].sum()
st

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [103]:
st = df.groupby(["Store",'Category'])["Sales"].sum()
st

Store  Category
S1     A           220
       B           500
S2     A           350
       B           430
Name: Sales, dtype: int64

#### Aggregation

In [104]:
df['Sales'].mean()

187.5

In [105]:
df['Sales'].median()

190.0

In [106]:
df['Sales'].mode()

0    200
Name: Sales, dtype: int64

In [107]:
df['Sales'].max()

300

In [108]:
df['Sales'].min()

100

In [109]:
df['Sales'].std()

66.06274074155351

In [110]:
df['Sales'].count()

8

In [114]:
df['Sales'].agg(['count','sum','mean','median','max','min','std'])

count        8.000000
sum       1500.000000
mean       187.500000
median     190.000000
max        300.000000
min        100.000000
std         66.062741
Name: Sales, dtype: float64

In [115]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  8 non-null      object
 1   Store     8 non-null      object
 2   Sales     8 non-null      int64
 3   Quantity  8 non-null      int64
 4   Date      8 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 452.0+ bytes

In [116]:
df.describe()

            Sales   Quantity                 Date
count    8.000000   8.000000                    8
mean   187.500000  15.375000  2023-01-04 12:00:00
min    100.000000   8.000000  2023-01-01 00:00:00
25%    142.500000  11.500000  2023-01-02 18:00:00
50%    190.000000  15.000000  2023-01-04 12:00:00
75%    212.500000  18.500000  2023-01-06 06:00:00
max    300.000000  25.000000  2023-01-08 00:00:00
std     66.062741   5.553313                  NaN

### PivotTables

In [117]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    573     36   John  January      Q1
1  2023-01-02       B   West    993     10   Mary  January      Q1
2  2023-01-03       C  North    209     96    Bob  January      Q1
3  2023-01-04       D  South    338     36  Alice  January      Q1
4  2023-01-05       A   East    546     94   John  January      Q1
5  2023-01-06       B   West    237     58   Mary  January      Q1
6  2023-01-07       C  North    560     56    Bob  January      Q1
7  2023-01-08       D  South    534     48  Alice  January      Q1
8  2023-01-09       A   East    726     67   John  January      Q1
9  2023-01-10       B   West    588     19   Mary  January      Q1
10 2023-01-11       C  North    884     31    Bob  January      Q1
11 2023-01-12       D  South    155     82  Alice  January      Q1
12 2023-01-13       A   East    982     16   John  January      Q1
13 2023-01-14       B   West    836     93   Mary  January      Q1
14 2023-01-15       C  North    895     92    Bob  January      Q1
15 2023-01-16       D  South    643     27  Alice  January      Q1
16 2023-01-17       A   East    882     70   John  January      Q1
17 2023-01-18       B   West    221     89   Mary  January      Q1
18 2023-01-19       C  North    919     36    Bob  January      Q1
19 2023-01-20       D  South    718     58  Alice  January      Q1

In [118]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product')

Product      A      B      C      D
Region
East     741.8    NaN    NaN    NaN
North      NaN    NaN  693.4    NaN
South      NaN    NaN    NaN  477.6
West       NaN  575.0    NaN    NaN

In [119]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product',aggfunc='median')

Product      A      B      C      D
Region
East     726.0    NaN    NaN    NaN
North      NaN    NaN  884.0    NaN
South      NaN    NaN    NaN  534.0
West       NaN  588.0    NaN    NaN

In [120]:
picot2 = pd.pivot_table(df,values=['Sales','Units'],index='Region',columns='Product')
picot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     741.8    NaN    NaN    NaN  56.6   NaN   NaN   NaN
North      NaN    NaN  693.4    NaN   NaN   NaN  62.2   NaN
South      NaN    NaN    NaN  477.6   NaN   NaN   NaN  50.2
West       NaN  575.0    NaN    NaN   NaN  53.8   NaN   NaN

#### Cross Tables

In [121]:
pd.crosstab(df['Region'],df['Product'])  #used for Counting

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

### Operations

In [146]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [130]:
df1.shape

(5, 3)

In [131]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [132]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [133]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [128]:
df1['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

#### DataFrames Applying Functions

In [147]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [148]:
def square(x):
    return x**2

In [149]:
df1['D']= df1["B"].apply(square)

In [150]:
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500

In [151]:
df1['E']= df1["B"].apply(lambda x:x**3)

In [152]:
df1

   A   B    C     D       E
0  1  10  100   100    1000
1  2  20  200   400    8000
2  3  30  300   900   27000
3  4  40  400  1600   64000
4  5  50  500  2500  125000